feat(settings-tab): Color settings display depending on color approach
verocloud/obsidian-mindmap-nextgen pull request #75
Opened 2023-01-09 06:17 UTC by james-tindal

Implements #68.
"Use only default color" is removed and "Colouring approach" has a new option, "Single colour".
The colour settings are hidden when not usable.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/10291002/211249675-68a78dbf-1183-4691-a948-4ed819bf4af1.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/10291002/211250187-17ab7e0f-a458-43d2-a8cb-7b37f95be951.png">

<img width="653" alt="image" src="https://user-images.githubusercontent.com/10291002/211250082-6a6791df-245f-4076-ac87-b54fc4642149.png">

2023-01-09 19:23 UTC, MasterTuto requested changes
Review and do the requested changes.

2023-01-09 19:23 UTC, MasterTuto commented on src/settings-tab.ts
> +    function decide_display_colors(approach: MindMapSettings['coloring']) {
- change the function name to camelCase
- move it to the top (make it another method)
- Modify it so this function receives an array of Setting (for dynamic colors), a single one Settings for the default one, and the approach.

2023-01-09 19:23 UTC, MasterTuto commented on src/settings-tab.ts
>      new Setting(containerEl)
- move this new Setting to the previous line, right after the `=`, followed by a space char.

2023-01-09 19:23 UTC, MasterTuto commented on src/settings-tab.ts
>      new Setting(containerEl)
- move this new Setting to the previous line, right after the `=`, followed by a space char.

2023-01-09 19:23 UTC, MasterTuto commented on src/settings-tab.ts
>      new Setting(containerEl)
- move this new Setting to the previous line, right after the `=`, followed by a space char.

2023-01-09 19:23 UTC, MasterTuto commented on src/settings-tab.ts
>      new Setting(containerEl)
- move this new Setting to the previous line, right after the `=`, followed by a space char.

2023-01-09 19:23 UTC, MasterTuto commented on src/settings-tab.ts
> +    decide_display_colors(this.plugin.settings.coloring)
- modify the function name to camelCase, as explained in previous reviews.

2023-01-09 23:06 UTC, MasterTuto requested changes
Just forgot this one.

2023-01-09 23:06 UTC, MasterTuto commented on src/settings-tab.ts
> +        branch: [],
- type this empty array `as Setting[]`.

2023-01-10 00:04 UTC, james-tindal commented
Made changes slightly different to what you suggested. decideDisplayColors is now a method with no arguments.
Are you OK with the loose ColorSettings type at the top level or should I put that in another file?

2023-01-13 04:39 UTC, MasterTuto approved these changes

2023-01-13 04:40 UTC, merged