feat: use document title as root node (optionally)
verocloud/obsidian-mindmap-nextgen pull request #77
Opened 2023-01-09 07:59 UTC by james-tindal

Implements #60.

With one top-level heading:
<img width="353" alt="" src="https://user-images.githubusercontent.com/10291002/211262336-a87f6009-72f1-45a3-a9d0-1903c10c955e.png">

With multiple top-level headings:
<img width="289" alt="" src="https://user-images.githubusercontent.com/10291002/211262258-ef87c2bd-d860-44aa-a05d-f4e7415258e5.png">

2023-01-09 19:55 UTC, MasterTuto requested changes
Thanks for leaving your PR, I'd be glad if you made the changes I have requests.

Thanks for your contribution.

2023-01-09 19:55 UTC, MasterTuto commented on src/mindmap-view.ts
> +    const rootWithTitle =
- make a new method to that takes root and returns a new root with title, this new method must be named as camelCase.
- Replace the multiple ternary operators with `if` clauses

2023-01-09 22:18 UTC, AdrianSimionov commented
Can we please add documentation and a front-matter option on top of the plugin settings? The front-matter option will take precedence and be applied only to the current .md file.

2023-01-10 00:44 UTC, james-tindal commented
I'll work on the front matter issues tomorrow morning and write it up in the readme

2023-01-13 04:52 UTC, MasterTuto approved these changes

2023-01-16 19:38 UTC, james-tindal commented
@AdrianSimionov I followed the <img width="154" alt="image" src="https://user-images.githubusercontent.com/10291002/212754227-6eb1d32f-e9d3-45ff-abf3-3a0419056ed7.png">, resolved the conflicts, merged and committed, but I don't have permission to push from the CLI.

2023-01-16 21:27 UTC, james-tindal commented
I can merge it differently though so that shouldn't be a problem.

2023-01-16 21:45 UTC, james-tindal commented
I noticed the map doesn't update when the setting changes. PR #86 (multiple tabs) sets up some stuff that I will base this functionality on, so I'm waiting on that.

2023-01-23 23:39 UTC, merged